import { Product } from '../components/ProductListingPage'

// Product catalog based on the geometric design collection
const productCatalog: Product[] = [
  // Pure Cube - White
  {
    id: 'pure-cube-white',
    name: 'Pure Cube',
    brand: 'Market Street',
    price: 49.00,
    image: '/images/products/pure-cube-white-1.png',
    images: [
      '/images/products/pure-cube-white-1.png',
      '/images/products/pure-cube-white-2.png',
      '/images/products/pure-cube-white-3.png',
      '/images/products/pure-cube-white-4.png',
    ],
    category: 'Geometric',
    subcategory: 'Cubes',
    color: 'White',
    colors: ['White', 'Black', 'Gray'],
    size: ['S', 'M', 'L'],
    inStock: true,
    stockQuantity: 24,
    storeAvailable: true,
    rating: 4.8,
    reviewCount: 124,
    isNew: true,
  },
  // Pure Cube - Black
  {
    id: 'pure-cube-black',
    name: 'Pure Cube',
    brand: 'Market Street',
    price: 49.00,
    image: '/images/products/pure-cube-black-1.png',
    images: [
      '/images/products/pure-cube-black-1.png',
      '/images/products/pure-cube-black-2.png',
      '/images/products/pure-cube-black-3.png',
      '/images/products/pure-cube-black-4.png',
    ],
    category: 'Geometric',
    subcategory: 'Cubes',
    color: 'Black',
    colors: ['White', 'Black', 'Gray'],
    size: ['S', 'M', 'L'],
    inStock: false,
    stockQuantity: 0,
    rating: 4.9,
    reviewCount: 89,
  },
  // Pure Cube - Gray
  {
    id: 'pure-cube-gray',
    name: 'Pure Cube',
    brand: 'Market Street',
    price: 49.00,
    image: '/images/products/pure-cube-gray-1.png',
    images: [
      '/images/products/pure-cube-gray-1.png',
      '/images/products/pure-cube-gray-2.png',
      '/images/products/pure-cube-gray-3.png',
      '/images/products/pure-cube-gray-4.png',
    ],
    category: 'Geometric',
    subcategory: 'Cubes',
    color: 'Gray',
    colors: ['White', 'Black', 'Gray'],
    size: ['S', 'M', 'L'],
    inStock: true,
    stockQuantity: 8,
    rating: 4.7,
    reviewCount: 56,
  },
  // Solid Cylinder
  {
    id: 'solid-cylinder',
    name: 'Solid Cylinder',
    brand: 'Market Street',
    price: 59.00,
    image: '/images/products/solid-cylinder-1.png',
    images: [
      '/images/products/solid-cylinder-1.png',
      '/images/products/solid-cylinder-2.png',
      '/images/products/solid-cylinder-3.png',
    ],
    category: 'Geometric',
    subcategory: 'Cylinders',
    size: ['S', 'M', 'L'],
    inStock: true,
    stockQuantity: 50,
    storeAvailable: true,
    rating: 4.6,
    reviewCount: 78,
    isBestSeller: true,
  },
  // Soft Sphere
  {
    id: 'soft-sphere',
    name: 'Soft Sphere',
    brand: 'Market Street',
    price: 45.00,
    originalPrice: 55.00,
    image: '/images/products/soft-sphere-1.png',
    images: [
      '/images/products/soft-sphere-1.png',
      '/images/products/soft-sphere-2.png',
      '/images/products/soft-sphere-3.png',
      '/images/products/soft-sphere-4.png',
    ],
    category: 'Geometric',
    subcategory: 'Spheres',
    size: ['S', 'M', 'L', 'XL'],
    inStock: true,
    stockQuantity: 15,
    rating: 4.5,
    reviewCount: 92,
  },
  // Fine Cone
  {
    id: 'fine-cone',
    name: 'Fine Cone',
    brand: 'Market Street',
    price: 39.00,
    image: '/images/products/fine-cone-1.png',
    images: [
      '/images/products/fine-cone-1.png',
      '/images/products/fine-cone-2.png',
      '/images/products/fine-cone-3.png',
      '/images/products/fine-cone-4.png',
    ],
    category: 'Geometric',
    subcategory: 'Cones',
    size: ['S', 'M', 'L'],
    inStock: true,
    stockQuantity: 32,
    rating: 4.4,
    reviewCount: 45,
  },
  // Steady Prism
  {
    id: 'steady-prism',
    name: 'Steady Prism',
    brand: 'Market Street',
    price: 65.00,
    image: '/images/products/steady-prism-1.png',
    images: [
      '/images/products/steady-prism-1.png',
      '/images/products/steady-prism-2.png',
      '/images/products/steady-prism-3.png',
      '/images/products/steady-prism-4.png',
    ],
    category: 'Geometric',
    subcategory: 'Prisms',
    size: ['M', 'L', 'XL'],
    inStock: true,
    stockQuantity: 18,
    rating: 4.7,
    reviewCount: 67,
    isNew: true,
  },
  // Dual Forms
  {
    id: 'dual-forms',
    name: 'Dual Forms',
    brand: 'Market Street',
    price: 79.00,
    image: '/images/products/dual-forms-1.png',
    images: [
      '/images/products/dual-forms-1.png',
      '/images/products/dual-forms-2.png',
      '/images/products/dual-forms-3.png',
      '/images/products/dual-forms-4.png',
    ],
    category: 'Sets',
    subcategory: 'Pairs',
    size: ['M', 'L'],
    inStock: true,
    stockQuantity: 5,
    rating: 4.8,
    reviewCount: 34,
    isLimitedEdition: true,
  },
  // Vertical Set
  {
    id: 'vertical-set',
    name: 'Vertical Set',
    brand: 'Market Street',
    price: 89.00,
    originalPrice: 110.00,
    image: '/images/products/vertical-set-1.png',
    images: [
      '/images/products/vertical-set-1.png',
      '/images/products/vertical-set-2.png',
      '/images/products/vertical-set-3.png',
      '/images/products/vertical-set-4.png',
    ],
    category: 'Sets',
    subcategory: 'Collections',
    size: ['S', 'M', 'L'],
    inStock: true,
    stockQuantity: 42,
    storeAvailable: true,
    rating: 4.9,
    reviewCount: 156,
    isBestSeller: true,
  },
  // Offset Pair
  {
    id: 'offset-pair',
    name: 'Offset Pair',
    brand: 'Market Street',
    price: 69.00,
    image: '/images/products/offset-pair-1.png',
    images: [
      '/images/products/offset-pair-1.png',
      '/images/products/offset-pair-2.png',
      '/images/products/offset-pair-3.png',
    ],
    category: 'Sets',
    subcategory: 'Pairs',
    size: ['M', 'L'],
    inStock: false,
    stockQuantity: 0,
    rating: 4.6,
    reviewCount: 28,
  },
  // Tilted Column
  {
    id: 'tilted-column',
    name: 'Tilted Column',
    brand: 'Market Street',
    price: 55.00,
    image: '/images/products/tilted-column-1.png',
    images: [
      '/images/products/tilted-column-1.png',
      '/images/products/tilted-column-2.png',
    ],
    category: 'Geometric',
    subcategory: 'Columns',
    size: ['S', 'M', 'L', 'XL'],
    inStock: true,
    stockQuantity: 27,
    rating: 4.3,
    reviewCount: 19,
  },
  // Spiral Accent
  {
    id: 'spiral-accent',
    name: 'Spiral Accent',
    brand: 'Market Street',
    price: 75.00,
    image: '/images/products/spiral-accent-1.png',
    images: [
      '/images/products/spiral-accent-1.png',
      '/images/products/spiral-accent-2.png',
      '/images/products/spiral-accent-3.png',
    ],
    category: 'Abstract',
    subcategory: 'Spirals',
    size: ['M', 'L'],
    inStock: true,
    stockQuantity: 11,
    rating: 4.8,
    reviewCount: 41,
    isNew: true,
  },
  // Floating Disk - White
  {
    id: 'floating-disk-white',
    name: 'Floating Disk',
    brand: 'Market Street',
    price: 42.00,
    image: '/images/products/floating-disk-white-1.png',
    images: [
      '/images/products/floating-disk-white-1.png',
      '/images/products/floating-disk-white-2.png',
    ],
    category: 'Geometric',
    subcategory: 'Disks',
    color: 'White',
    colors: ['White', 'Charcoal'],
    size: ['S', 'M', 'L'],
    inStock: true,
    stockQuantity: 50,
    storeAvailable: true,
    rating: 4.5,
    reviewCount: 63,
  },
  // Floating Disk - Charcoal
  {
    id: 'floating-disk-charcoal',
    name: 'Floating Disk',
    brand: 'Market Street',
    price: 42.00,
    image: '/images/products/floating-disk-charcoal-1.png',
    images: [
      '/images/products/floating-disk-charcoal-1.png',
      '/images/products/floating-disk-charcoal-2.png',
    ],
    category: 'Geometric',
    subcategory: 'Disks',
    color: 'Charcoal',
    colors: ['White', 'Charcoal'],
    size: ['S', 'M', 'L'],
    inStock: true,
    stockQuantity: 3,
    rating: 4.6,
    reviewCount: 47,
  },
  // Flow Form I
  {
    id: 'flow-form-i',
    name: 'Flow Form I',
    brand: 'Market Street',
    price: 85.00,
    image: '/images/products/flow-form-i-1.png',
    images: [
      '/images/products/flow-form-i-1.png',
      '/images/products/flow-form-i-2.png',
      '/images/products/flow-form-i-3.png',
    ],
    category: 'Abstract',
    subcategory: 'Flow',
    size: ['M', 'L', 'XL'],
    inStock: true,
    stockQuantity: 35,
    rating: 4.9,
    reviewCount: 72,
    isBestSeller: true,
  },
  // Flow Form II
  {
    id: 'flow-form-ii',
    name: 'Flow Form II',
    brand: 'Market Street',
    price: 85.00,
    image: '/images/products/flow-form-ii-1.png',
    images: [
      '/images/products/flow-form-ii-1.png',
      '/images/products/flow-form-ii-2.png',
    ],
    category: 'Abstract',
    subcategory: 'Flow',
    size: ['M', 'L', 'XL'],
    inStock: false,
    stockQuantity: 0,
    rating: 4.7,
    reviewCount: 38,
  },
  // Micro Spiral
  {
    id: 'micro-spiral',
    name: 'Micro Spiral',
    brand: 'Market Street',
    price: 35.00,
    originalPrice: 45.00,
    image: '/images/products/micro-spiral-1.png',
    images: [
      '/images/products/micro-spiral-1.png',
    ],
    category: 'Abstract',
    subcategory: 'Spirals',
    size: ['XS', 'S', 'M'],
    inStock: true,
    stockQuantity: 48,
    rating: 4.4,
    reviewCount: 89,
  },
  // Contrast Plane
  {
    id: 'contrast-plane',
    name: 'Contrast Plane',
    brand: 'Market Street',
    price: 52.00,
    image: '/images/products/contrast-plane-1.png',
    images: [
      '/images/products/contrast-plane-1.png',
      '/images/products/contrast-plane-2.png',
    ],
    category: 'Geometric',
    subcategory: 'Planes',
    size: ['S', 'M', 'L'],
    inStock: true,
    stockQuantity: 21,
    rating: 4.5,
    reviewCount: 31,
  },
  // Shadow Edge
  {
    id: 'shadow-edge',
    name: 'Shadow Edge',
    brand: 'Market Street',
    price: 58.00,
    image: '/images/products/shadow-edge-1.png',
    images: [
      '/images/products/shadow-edge-1.png',
      '/images/products/shadow-edge-2.png',
      '/images/products/shadow-edge-3.png',
    ],
    category: 'Abstract',
    subcategory: 'Edges',
    size: ['M', 'L'],
    inStock: true,
    stockQuantity: 14,
    rating: 4.6,
    reviewCount: 24,
    isOnlineOnly: true,
  },
  // Polished Fold
  {
    id: 'polished-fold',
    name: 'Polished Fold',
    brand: 'Market Street',
    price: 72.00,
    image: '/images/products/polished-fold-1.png',
    images: [
      '/images/products/polished-fold-1.png',
      '/images/products/polished-fold-2.png',
      '/images/products/polished-fold-3.png',
      '/images/products/polished-fold-4.png',
    ],
    category: 'Abstract',
    subcategory: 'Folds',
    size: ['S', 'M', 'L', 'XL'],
    inStock: true,
    stockQuantity: 9,
    rating: 4.8,
    reviewCount: 52,
    isNew: true,
  },
  // Fusion Block
  {
    id: 'fusion-block',
    name: 'Fusion Block',
    brand: 'Market Street',
    price: 95.00,
    image: '/images/products/fusion-block-1.png',
    images: [
      '/images/products/fusion-block-1.png',
      '/images/products/fusion-block-2.png',
      '/images/products/fusion-block-3.png',
      '/images/products/fusion-block-4.png',
    ],
    category: 'Sets',
    subcategory: 'Blocks',
    size: ['M', 'L', 'XL'],
    inStock: true,
    stockQuantity: 50,
    storeAvailable: true,
    rating: 4.9,
    reviewCount: 87,
    isBestSeller: true,
  },
  // Fusion Prism - White
  {
    id: 'fusion-prism-white',
    name: 'Fusion Prism',
    brand: 'Market Street',
    price: 88.00,
    image: '/images/products/fusion-prism-white-1.png',
    images: [
      '/images/products/fusion-prism-white-1.png',
      '/images/products/fusion-prism-white-2.png',
      '/images/products/fusion-prism-white-3.png',
      '/images/products/fusion-prism-white-4.png',
    ],
    category: 'Geometric',
    subcategory: 'Prisms',
    color: 'White',
    colors: ['White', 'Charcoal'],
    size: ['M', 'L', 'XL'],
    inStock: true,
    stockQuantity: 19,
    rating: 4.7,
    reviewCount: 43,
  },
  // Fusion Prism - Charcoal
  {
    id: 'fusion-prism-charcoal',
    name: 'Fusion Prism',
    brand: 'Market Street',
    price: 88.00,
    image: '/images/products/fusion-prism-charcoal-1.png',
    images: [
      '/images/products/fusion-prism-charcoal-1.png',
      '/images/products/fusion-prism-charcoal-2.png',
      '/images/products/fusion-prism-charcoal-3.png',
      '/images/products/fusion-prism-charcoal-4.png',
    ],
    category: 'Geometric',
    subcategory: 'Prisms',
    color: 'Charcoal',
    colors: ['White', 'Charcoal'],
    size: ['M', 'L', 'XL'],
    inStock: false,
    stockQuantity: 0,
    rating: 4.8,
    reviewCount: 61,
    isNew: true,
  },
  // Unity Sphere
  {
    id: 'unity-sphere',
    name: 'Unity Sphere',
    brand: 'Market Street',
    price: 68.00,
    originalPrice: 85.00,
    image: '/images/products/unity-sphere-1.png',
    images: [
      '/images/products/unity-sphere-1.png',
      '/images/products/unity-sphere-2.png',
      '/images/products/unity-sphere-3.png',
      '/images/products/unity-sphere-4.png',
    ],
    category: 'Geometric',
    subcategory: 'Spheres',
    size: ['S', 'M', 'L', 'XL'],
    inStock: true,
    stockQuantity: 28,
    rating: 4.6,
    reviewCount: 98,
  },
  // Base Module
  {
    id: 'base-module',
    name: 'Base Module',
    brand: 'Market Street',
    price: 45.00,
    image: '/images/products/base-module-1.png',
    images: [
      '/images/products/base-module-1.png',
      '/images/products/base-module-2.png',
      '/images/products/base-module-3.png',
      '/images/products/base-module-4.png',
    ],
    category: 'Modular',
    subcategory: 'Bases',
    size: ['S', 'M', 'L'],
    inStock: true,
    stockQuantity: 45,
    storeAvailable: true,
    rating: 4.5,
    reviewCount: 76,
  },
  // Core Assembly
  {
    id: 'core-assembly',
    name: 'Core Assembly',
    brand: 'Market Street',
    price: 125.00,
    image: '/images/products/core-assembly-1.png',
    images: [
      '/images/products/core-assembly-1.png',
      '/images/products/core-assembly-2.png',
      '/images/products/core-assembly-3.png',
    ],
    category: 'Modular',
    subcategory: 'Assemblies',
    size: ['M', 'L', 'XL'],
    inStock: true,
    stockQuantity: 7,
    rating: 4.9,
    reviewCount: 34,
    isLimitedEdition: true,
  },
  // Compact Layer
  {
    id: 'compact-layer',
    name: 'Compact Layer',
    brand: 'Market Street',
    price: 55.00,
    image: '/images/products/compact-layer-1.png',
    images: [
      '/images/products/compact-layer-1.png',
      '/images/products/compact-layer-2.png',
      '/images/products/compact-layer-3.png',
    ],
    category: 'Modular',
    subcategory: 'Layers',
    size: ['S', 'M', 'L'],
    inStock: true,
    stockQuantity: 33,
    rating: 4.4,
    reviewCount: 42,
  },
  // Twin Towers - Small
  {
    id: 'twin-towers-small',
    name: 'Twin Towers',
    brand: 'Market Street',
    price: 75.00,
    image: '/images/products/twin-towers-small-1.png',
    images: [
      '/images/products/twin-towers-small-1.png',
      '/images/products/twin-towers-small-2.png',
      '/images/products/twin-towers-small-3.png',
    ],
    category: 'Sets',
    subcategory: 'Towers',
    color: 'Small',
    colors: ['Small', 'Medium', 'Large'],
    size: ['S'],
    inStock: true,
    stockQuantity: 22,
    rating: 4.7,
    reviewCount: 28,
  },
  // Twin Towers - Medium
  {
    id: 'twin-towers-medium',
    name: 'Twin Towers',
    brand: 'Market Street',
    price: 95.00,
    image: '/images/products/twin-towers-medium-1.png',
    images: [
      '/images/products/twin-towers-medium-1.png',
      '/images/products/twin-towers-medium-2.png',
      '/images/products/twin-towers-medium-3.png',
    ],
    category: 'Sets',
    subcategory: 'Towers',
    color: 'Medium',
    colors: ['Small', 'Medium', 'Large'],
    size: ['M'],
    inStock: false,
    stockQuantity: 0,
    rating: 4.8,
    reviewCount: 45,
    isBestSeller: true,
  },
  // Twin Towers - Large
  {
    id: 'twin-towers-large',
    name: 'Twin Towers',
    brand: 'Market Street',
    price: 125.00,
    originalPrice: 145.00,
    image: '/images/products/twin-towers-large-1.png',
    images: [
      '/images/products/twin-towers-large-1.png',
      '/images/products/twin-towers-large-2.png',
      '/images/products/twin-towers-large-3.png',
    ],
    category: 'Sets',
    subcategory: 'Towers',
    color: 'Large',
    colors: ['Small', 'Medium', 'Large'],
    size: ['L'],
    inStock: true,
    stockQuantity: 12,
    rating: 4.9,
    reviewCount: 67,
  },
  // Sky Column
  {
    id: 'sky-column',
    name: 'Sky Column',
    brand: 'Market Street',
    price: 110.00,
    image: '/images/products/sky-column-1.png',
    images: [
      '/images/products/sky-column-1.png',
      '/images/products/sky-column-2.png',
    ],
    category: 'Geometric',
    subcategory: 'Columns',
    size: ['M', 'L', 'XL'],
    inStock: true,
    stockQuantity: 16,
    rating: 4.6,
    reviewCount: 23,
    isNew: true,
  },
  // Layer One
  {
    id: 'layer-one',
    name: 'Layer One',
    brand: 'Market Street',
    price: 38.00,
    image: '/images/products/layer-one-1.png',
    images: [
      '/images/products/layer-one-1.png',
      '/images/products/layer-one-2.png',
    ],
    category: 'Modular',
    subcategory: 'Layers',
    size: ['S', 'M', 'L'],
    inStock: true,
    stockQuantity: 50,
    rating: 4.3,
    reviewCount: 54,
  },
  // Layer Two
  {
    id: 'layer-two',
    name: 'Layer Two',
    brand: 'Market Street',
    price: 42.00,
    image: '/images/products/layer-two-1.png',
    images: [
      '/images/products/layer-two-1.png',
      '/images/products/layer-two-2.png',
    ],
    category: 'Modular',
    subcategory: 'Layers',
    size: ['S', 'M', 'L'],
    inStock: true,
    stockQuantity: 38,
    rating: 4.4,
    reviewCount: 39,
  },
  // Layer Grid
  {
    id: 'layer-grid',
    name: 'Layer Grid',
    brand: 'Market Street',
    price: 65.00,
    image: '/images/products/layer-grid-1.png',
    images: [
      '/images/products/layer-grid-1.png',
      '/images/products/layer-grid-2.png',
    ],
    category: 'Modular',
    subcategory: 'Grids',
    size: ['M', 'L', 'XL'],
    inStock: true,
    stockQuantity: 25,
    rating: 4.7,
    reviewCount: 31,
  },
  // Signature Form - White
  {
    id: 'signature-form-white',
    name: 'Signature Form',
    brand: 'Market Street',
    price: 150.00,
    image: '/images/products/signature-form-white-1.png',
    images: [
      '/images/products/signature-form-white-1.png',
      '/images/products/signature-form-white-2.png',
      '/images/products/signature-form-white-3.png',
    ],
    category: 'Premium',
    subcategory: 'Signature',
    color: 'White',
    colors: ['White', 'Silver', 'Black'],
    size: ['M', 'L', 'XL'],
    inStock: true,
    stockQuantity: 4,
    storeAvailable: true,
    rating: 5.0,
    reviewCount: 89,
    isLimitedEdition: true,
  },
  // Signature Form - Silver
  {
    id: 'signature-form-silver',
    name: 'Signature Form',
    brand: 'Market Street',
    price: 165.00,
    image: '/images/products/signature-form-silver-1.png',
    images: [
      '/images/products/signature-form-silver-1.png',
      '/images/products/signature-form-silver-2.png',
    ],
    category: 'Premium',
    subcategory: 'Signature',
    color: 'Silver',
    colors: ['White', 'Silver', 'Black'],
    size: ['M', 'L', 'XL'],
    inStock: true,
    stockQuantity: 50,
    rating: 4.9,
    reviewCount: 56,
    isLimitedEdition: true,
  },
  // Signature Form - Black
  {
    id: 'signature-form-black',
    name: 'Signature Form',
    brand: 'Market Street',
    price: 150.00,
    originalPrice: 180.00,
    image: '/images/products/signature-form-black-1.png',
    images: [
      '/images/products/signature-form-black-1.png',
      '/images/products/signature-form-black-2.png',
      '/images/products/signature-form-black-3.png',
    ],
    category: 'Premium',
    subcategory: 'Signature',
    color: 'Black',
    colors: ['White', 'Silver', 'Black'],
    size: ['M', 'L', 'XL'],
    inStock: false,
    stockQuantity: 0,
    rating: 4.8,
    reviewCount: 72,
  },
]

export function getProductsBySubcategory(
  category: string,
  subcategory?: string
): Product[] {
  // For the geometric products, map old categories to new ones
  const categoryMappings: Record<string, string[]> = {
    'Women': ['Geometric', 'Abstract', 'Premium'],
    'Men': ['Modular', 'Sets'],
    'Accessories': ['Geometric', 'Abstract', 'Modular'],
    'Sale': [], // Handled separately
  }

  if (!subcategory) {
    const allowedCategories = categoryMappings[category] || []
    if (allowedCategories.length === 0) {
      // Return all products
      return productCatalog
    }
    return productCatalog.filter(p => allowedCategories.includes(p.category))
  }

  // Filter by subcategory
  return productCatalog.filter(
    p => p.subcategory.toLowerCase() === subcategory.toLowerCase()
  )
}

export function getAllProducts(): Product[] {
  return productCatalog
}

export function getProductById(id: string): Product | undefined {
  return productCatalog.find(p => p.id === id)
}

export function getFeaturedProducts(): Product[] {
  return productCatalog.filter(p => p.isBestSeller || p.isNew).slice(0, 8)
}

export function getNewArrivals(): Product[] {
  return productCatalog.filter(p => p.isNew).slice(0, 4)
}

export function getSaleProducts(): Product[] {
  return productCatalog.filter(p => p.originalPrice && p.originalPrice > p.price)
}
